#! /usr/bin/perl

use strict;
use warnings;

use DB_File;

my $db = shift;
my %nodelist;

unless (tie(%nodelist, 'DB_File', "$db.$$", O_RDWR|O_CREAT, 0644)) {
	die "Cannot create database: $!\n";
}
my $line = 0;
while (<>) {
	chomp();
	$line++;
	if (/^;A FidoNet Nodelist for \S+, \S+ \d+, \d+ -- Day number (\d+)/) {
		$nodelist{"daynum"} = $1;
	}
	next if /^;/;
	next if /^\x1a?\s*$/;
	unless (/^([^,]*),([^,]+),([^,]+),([^,]+),([^,]+),([^,]+),([^,]+)(?:,(.*))?$/)
	{	error("Can't parse line $line:\n$_");
		next;
	}
	my ($keyword, $zone, $net, $node);
	($keyword, $node) = ($1, $2);
	unless ($keyword =~ /^(Zone|Region|Host|Hub|Hold|Down|Pvt|)$/)
	{	error("unknown keyword $keyword in line $line:\n$_");
		next;
	}
	if ($keyword eq "Zone") {
		$zone = $net = $node;
		$node = 0;
	} elsif ($keyword eq "Region" || $keyword eq "Host") {
		$net = $node;
		$node = 0;
	}
	$nodelist{"$zone:$net/$node"} = $_;
}
untie(%nodelist);

rename("$db.$$", $db);

exit(0);

sub error {
	print STDERR "$_[0]\n";
}

